import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../../globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { DashboardSidebar } from "@/components/admin-dashboard/DashboardSidebar";
import { DashboardHeader } from "@/components/admin-dashboard/DashboardHeader";

const PoppinsFont = Poppins({
  variable: "--font-poppins",
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
  ],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface DashboardLayoutProps {
  children: React.ReactNode;
}

export default function AdminDashboardLayout({
  children,
}: DashboardLayoutProps) {
  return (
    <html lang="en">
      <body className={`${PoppinsFont.variable} antialiased`}>
        <SidebarProvider>
          <div className="flex min-h-screen w-full">
            <DashboardSidebar />
            <div className="flex flex-1 flex-col overflow-hidden">
              <DashboardHeader />
              <main className="flex-1 overflow-auto bg-background p-4 lg:p-6">
                {children}
              </main>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
